# Generated by Django 4.2.2 on 2023-07-10 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': [('can_read_article', '有权限读文章')], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
    ]
