class ResponseMessage:
    INVALID_DATA = "Неверный запрос данных."
    CREATE_FUTURE_SLOTS = "Вы пытаетесь создать слот в прошлом, пожалуйста смотрите в будущее."
    CONFLICTING_SLOTS = "Невозможно создать слот из-за конфликта между {} и {}."
    CALENDAR_SLOTS_NOT_FOUND = "Календарный слот не найден!"
    USER_NOT_FOUND = "Пользователь не найден, попробуйте еще раз!"
    CALENDAR_SLOT_ALREADY_BOOKED = "Календарный слот уже занят, выберите другой!"
    CALENDAR_SLOT_EXPIRED = "Вы пытаетесь создать слот в прошлом, попробуйте другой!"
    MISSING_KEY = "Пропущен обязательный ключ {} !"
    REGISTRATION_REQUIRED = "Вы должны быть авторизованы для дальнейших действий."
    BOOKING_NOT_FOUND = "Событие не найдено на выбранный слот"