# Generated by Django 4.2.2 on 2023-07-03 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalenderSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='\n    Django auto populates timestamp whenever a slot is created by a user.\n    ')),
                ('start_time', models.DateTimeField(help_text='\n    Contains the start time of the slot.\n    ')),
                ('end_time', models.DateTimeField(help_text='\n    Contains the end time of the slot.\n    ')),
                ('belongs_to', models.ForeignKey(help_text='\n    Stores the user the slot belogs to\n    ', on_delete=django.db.models.deletion.CASCADE, related_name='created_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SlotBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_at', models.DateTimeField(auto_now_add=True, help_text='\n    Django auto populates timestamp whenever a slot is booked\n    ')),
                ('description', models.TextField(help_text='\n    Contains some booking data entered by the person who booked the slot.\n    ', null=True)),
                ('booked_by', models.ForeignKey(help_text='\n    Contains the user who has booked the slot. If it was booked by an anonymous user, it is None.\n    ', on_delete=django.db.models.deletion.CASCADE, related_name='booked_slots', to=settings.AUTH_USER_MODEL)),
                ('slot', models.OneToOneField(help_text='\n    References to the slot that is booked.\n    ', on_delete=django.db.models.deletion.CASCADE, related_name='booking_details', to='calender.calenderslot')),
            ],
            options={
                'ordering': ['-booked_at'],
            },
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
